### ISSUE TITLE
Call to localhost/127.0.0.1:54310 failed on connection

### ISSUE THREAD

**Issue by prayagupa** [prayagupd/smartad#2]
spark 1.2.0 with hadoop 2.7.0

https://github.com/prayagupd/smartad/tree/master/smartad-backend/smartad-spark

```
$ /usr/local/spark-1.2.0/bin/spark-submit  --class "SongPlayCountApp" --master spark://prayagupd:7077 target/scala-2.10/smartad-spark-songplaycount_2.10-1.0.jar 

15/05/13 18:27:00 WARN util.Utils: Your hostname, prayagupd resolves to a loopback address: 127.0.1.1; using 172.17.0.50 instead (on interface eth0)
15/05/13 18:27:00 WARN util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
15/05/13 18:27:00 INFO spark.SecurityManager: Changing view acls to: prayagupd
15/05/13 18:27:00 INFO spark.SecurityManager: Changing modify acls to: prayagupd
15/05/13 18:27:00 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(prayagupd); users with modify permissions: Set(prayagupd)
15/05/13 18:27:02 INFO slf4j.Slf4jLogger: Slf4jLogger started
15/05/13 18:27:02 INFO Remoting: Starting remoting
15/05/13 18:27:03 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@prayagupd.local:44343]
15/05/13 18:27:03 INFO util.Utils: Successfully started service 'sparkDriver' on port 44343.
15/05/13 18:27:03 INFO spark.SparkEnv: Registering MapOutputTracker
15/05/13 18:27:03 INFO spark.SparkEnv: Registering BlockManagerMaster
15/05/13 18:27:03 INFO storage.DiskBlockManager: Created local directory at /tmp/spark-local-20150513182703-4f64
15/05/13 18:27:03 INFO storage.MemoryStore: MemoryStore started with capacity 265.4 MB
15/05/13 18:27:04 INFO spark.HttpFileServer: HTTP File server directory is /tmp/spark-286f689d-83c3-48b6-a02d-03fb11313fc4
15/05/13 18:27:04 INFO spark.HttpServer: Starting HTTP Server
15/05/13 18:27:05 INFO server.Server: jetty-8.y.z-SNAPSHOT
15/05/13 18:27:05 INFO server.AbstractConnector: Started SocketConnector@0.0.0.0:34861
15/05/13 18:27:05 INFO util.Utils: Successfully started service 'HTTP file server' on port 34861.
15/05/13 18:27:10 INFO server.Server: jetty-8.y.z-SNAPSHOT
15/05/13 18:27:10 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:4040
15/05/13 18:27:10 INFO util.Utils: Successfully started service 'SparkUI' on port 4040.
15/05/13 18:27:10 INFO ui.SparkUI: Started SparkUI at http://prayagupd.local:4040
15/05/13 18:27:10 INFO spark.SparkContext: Added JAR file:/packup/workspace.programming/workspace.scala/smartad/smartad-backend/smartad-spark/target/scala-2.10/smartad-spark-songplaycount_2.10-1.0.jar at http://172.17.0.50:34861/jars/smartad-spark-songplaycount_2.10-1.0.jar with timestamp 1431559630869
15/05/13 18:27:11 INFO client.AppClient$ClientActor: Connecting to master spark://prayagupd:7077...
15/05/13 18:27:12 INFO cluster.SparkDeploySchedulerBackend: Connected to Spark cluster with app ID app-20150513182712-0000
15/05/13 18:27:12 INFO client.AppClient$ClientActor: Executor added: app-20150513182712-0000/0 on worker-20150513180919-prayagupd.local-58906 (prayagupd.local:58906) with 4 cores
15/05/13 18:27:12 INFO cluster.SparkDeploySchedulerBackend: Granted executor ID app-20150513182712-0000/0 on hostPort prayagupd.local:58906 with 4 cores, 512.0 MB RAM
15/05/13 18:27:12 INFO client.AppClient$ClientActor: Executor updated: app-20150513182712-0000/0 is now RUNNING
15/05/13 18:27:14 INFO netty.NettyBlockTransferService: Server created on 48041
15/05/13 18:27:14 INFO storage.BlockManagerMaster: Trying to register BlockManager
15/05/13 18:27:14 INFO storage.BlockManagerMasterActor: Registering block manager prayagupd.local:48041 with 265.4 MB RAM, BlockManagerId(<driver>, prayagupd.local, 48041)
15/05/13 18:27:14 INFO storage.BlockManagerMaster: Registered BlockManager
15/05/13 18:27:16 INFO cluster.SparkDeploySchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
15/05/13 18:27:18 INFO storage.MemoryStore: ensureFreeSpace(32768) called with curMem=0, maxMem=278302556
15/05/13 18:27:18 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 32.0 KB, free 265.4 MB)
15/05/13 18:27:19 INFO storage.MemoryStore: ensureFreeSpace(4990) called with curMem=32768, maxMem=278302556
15/05/13 18:27:19 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 4.9 KB, free 265.4 MB)
15/05/13 18:27:19 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on prayagupd.local:48041 (size: 4.9 KB, free: 265.4 MB)
15/05/13 18:27:19 INFO storage.BlockManagerMaster: Updated info of block broadcast_0_piece0
15/05/13 18:27:19 INFO spark.SparkContext: Created broadcast 0 from textFile at SongPlayCountApp.scala:17
15/05/13 18:27:20 INFO client.AppClient$ClientActor: Executor updated: app-20150513182712-0000/0 is now LOADING
15/05/13 18:27:23 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 0 time(s).
15/05/13 18:27:24 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 1 time(s).
15/05/13 18:27:25 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 2 time(s).
15/05/13 18:27:26 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 3 time(s).
15/05/13 18:27:26 INFO cluster.SparkDeploySchedulerBackend: Registered executor: Actor[akka.tcp://sparkExecutor@prayagupd.local:55871/user/Executor#720336115] with ID 0
15/05/13 18:27:27 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 4 time(s).
15/05/13 18:27:27 INFO storage.BlockManagerMasterActor: Registering block manager prayagupd.local:36751 with 265.4 MB RAM, BlockManagerId(0, prayagupd.local, 36751)
15/05/13 18:27:28 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 5 time(s).
15/05/13 18:27:29 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 6 time(s).
15/05/13 18:27:30 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 7 time(s).
15/05/13 18:27:31 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 8 time(s).
15/05/13 18:27:32 INFO ipc.Client: Retrying connect to server: localhost/127.0.0.1:54310. Already tried 9 time(s).
Exception in thread "main" java.lang.RuntimeException: java.net.ConnectException: Call to localhost/127.0.0.1:54310 failed on connection exception: java.net.ConnectException: Connection refused
    at org.apache.hadoop.mapred.JobConf.getWorkingDirectory(JobConf.java:546)
    at org.apache.hadoop.mapred.FileInputFormat.setInputPaths(FileInputFormat.java:318)
    at org.apache.hadoop.mapred.FileInputFormat.setInputPaths(FileInputFormat.java:291)
    at org.apache.spark.SparkContext$$anonfun$26.apply(SparkContext.scala:696)
    at org.apache.spark.SparkContext$$anonfun$26.apply(SparkContext.scala:696)
    at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:170)
    at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:170)
    at scala.Option.map(Option.scala:145)
    at org.apache.spark.rdd.HadoopRDD.getJobConf(HadoopRDD.scala:170)
    at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:194)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:205)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:203)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:203)
    at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:205)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:203)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:203)
    at org.apache.spark.rdd.FilteredRDD.getPartitions(FilteredRDD.scala:29)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:205)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:203)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:203)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1328)
    at org.apache.spark.rdd.RDD.count(RDD.scala:910)
    at SongPlayCountApp$.main(SongPlayCountApp.scala:18)
    at SongPlayCountApp.main(SongPlayCountApp.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.ConnectException: Call to localhost/127.0.0.1:54310 failed on connection exception: java.net.ConnectException: Connection refused
    at org.apache.hadoop.ipc.Client.wrapException(Client.java:1099)
    at org.apache.hadoop.ipc.Client.call(Client.java:1075)
    at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
    at com.sun.proxy.$Proxy9.getProtocolVersion(Unknown Source)
    at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:396)
    at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:379)
    at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:119)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:238)
    at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:203)
    at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:89)
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1386)
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1404)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:254)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:123)
    at org.apache.hadoop.mapred.JobConf.getWorkingDirectory(JobConf.java:542)
    ... 34 more
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
    at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
    at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:489)
    at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:434)
    at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:560)
    at org.apache.hadoop.ipc.Client$Connection.access$2000(Client.java:184)
    at org.apache.hadoop.ipc.Client.getConnection(Client.java:1206)
    at org.apache.hadoop.ipc.Client.call(Client.java:1050)
    ... 48 more

```

Spark log

```
15/05/13 18:27:19 INFO worker.Worker: Asked to launch executor app-20150513182712-0000/0 for Smartad Spark SongPlaycount
15/05/13 18:27:21 INFO worker.ExecutorRunner: Launch command: "/usr/local/jdk1.7.0_65/bin/java" "-cp" "::/usr/local/spark-1.2.0/conf:/usr/local/spark-1.2.0/assembly/target/scala-2.10/spark-assembly-1.2.0-hadoop1.0.4.jar:/usr/local/hadoop-2.2.0/etc/hadoop:/usr/local/hadoop-2.2.0/etc/hadoop" "-XX:MaxPermSize=128m" "-Dspark.driver.port=44343" "-Xms512M" "-Xmx512M" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "akka.tcp://sparkDriver@prayagupd.local:44343/user/CoarseGrainedScheduler" "0" "prayagupd.local" "4" "app-20150513182712-0000" "akka.tcp://sparkWorker@prayagupd.local:58906/user/Worker"
15/05/13 18:27:32 INFO worker.Worker: Asked to kill executor app-20150513182712-0000/0
15/05/13 18:27:32 INFO worker.ExecutorRunner: Runner thread for executor app-20150513182712-0000/0 interrupted
15/05/13 18:27:32 INFO worker.ExecutorRunner: Killing process!
15/05/13 18:27:32 INFO worker.Worker: Executor app-20150513182712-0000/0 finished with state KILLED exitStatus 1
15/05/13 18:27:33 WARN remote.ReliableDeliverySupervisor: Association with remote system [akka.tcp://sparkExecutor@prayagupd.local:55871] has failed, address is now gated for [5000] ms. Reason is: [Disassociated].
15/05/13 18:27:33 INFO actor.LocalActorRef: Message [akka.remote.transport.ActorTransportAdapter$DisassociateUnderlying] from Actor[akka://sparkWorker/deadLetters] to Actor[akka://sparkWorker/system/transports/akkaprotocolmanager.tcp0/akkaProtocol-tcp%3A%2F%2FsparkWorker%40172.17.0.50%3A37235-2#1716441550] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
15/05/13 18:27:33 INFO actor.LocalActorRef: Message [akka.remote.EndpointWriter$AckIdleCheckTimer$] from Actor[akka://sparkWorker/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FsparkExecutor%40prayagupd.local%3A55871-1/endpointWriter#2092441145] to Actor[akka://sparkWorker/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FsparkExecutor%40prayagupd.local%3A55871-1/endpointWriter#2092441145] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

```

**Comment by prayagupd** [comment]
following error with `spark-1.1.1` and `hadoop 2.7.0`

```
15/05/14 12:10:23 INFO SongPlayCountApp$: => jobName "MainExample"
15/05/14 12:10:23 INFO SongPlayCountApp$: => pathToFiles "/user/hduser/alsobought/input"
15/05/14 12:10:24 INFO storage.MemoryStore: ensureFreeSpace(32768) called with curMem=0, maxMem=278302556
15/05/14 12:10:24 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 32.0 KB, free 265.4 MB)
15/05/14 12:10:24 INFO storage.MemoryStore: ensureFreeSpace(4990) called with curMem=32768, maxMem=278302556
15/05/14 12:10:24 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 4.9 KB, free 265.4 MB)
15/05/14 12:10:24 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:45385 (size: 4.9 KB, free: 265.4 MB)
15/05/14 12:10:24 INFO storage.BlockManagerMaster: Updated info of block broadcast_0_piece0
15/05/14 12:10:24 INFO spark.SparkContext: Created broadcast 0 from textFile at SongPlayCountApp.scala:49
Exception in thread "main" org.apache.hadoop.ipc.RemoteException: Server IPC version 9 cannot communicate with client version 4
	at org.apache.hadoop.ipc.Client.call(Client.java:1070)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
	at com.sun.proxy.$Proxy9.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:396)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:379)
	at org.apache.hadoop.hdfs.DFSClient.createRPCNamenode(DFSClient.java:119)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:238)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:203)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:89)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1386)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:66)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1404)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:254)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:123)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:238)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:187)
	at org.apache.spark.SparkHadoopWriter$.createPathFromString(SparkHadoopWriter.scala:185)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:939)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:849)
	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1164)
	at SongPlayCountApp$.main(SongPlayCountApp.scala:55)
	at SongPlayCountApp.main(SongPlayCountApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by prayagupd** [comment]
```
$ ll assembly/target/scala-2.10/
total 110456
drwxrwxr-x 2 prayagupd prayagupd      4096 May 13 18:00 ./
drwxrwxr-x 5 prayagupd prayagupd      4096 Feb 13 08:19 ../
-rw-rw-r-- 1 prayagupd prayagupd 113095117 Feb 13 08:23 spark-assembly-1.2.0-hadoop1.0.4.jar
```

needs to `spark-assembly-1.2.0-hadoop2.2.0.jar`
